# -*- coding: utf-8 -*-
"""Static build steps for dralialsherif-site-v2.

Run before committing:  python tools/build.py

What it does
------------
1. Regenerates the Arabic entry point  ar/index.html  from  index.html
   (rewrites relative asset paths, forces Arabic, sets the Arabic canonical).
2. Refreshes <lastmod> in sitemap.xml to today.

It does NOT touch the workshop pages — run  python tools/gen_workshops.py  for those.
"""
import re
import datetime
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE_URL = "https://dralialsherif.github.io/dralialsherif-site-v2"
TODAY = datetime.date.today().isoformat()


def build_ar():
    src = (ROOT / "index.html").read_text(encoding="utf-8")

    # 1. lang / dir
    out = src.replace('<html lang="en" dir="ltr">', '<html lang="ar" dir="rtl">', 1)

    # 2. relative resource paths -> one level up (ar/ is a subdirectory)
    out = re.sub(r'(href|src)="(assets/|workshops/|articles/|media-kit\.html|site\.webmanifest|404\.html)',
                 r'\1="../\2', out)

    # 3. canonical + og:url point at the Arabic URL; keep hreflang lines intact
    out = out.replace(f'<link rel="canonical" href="{SITE_URL}/" />',
                      f'<link rel="canonical" href="{SITE_URL}/ar/" />', 1)
    out = out.replace(f'<meta property="og:url" content="{SITE_URL}/" />',
                      f'<meta property="og:url" content="{SITE_URL}/ar/" />', 1)
    out = out.replace('<meta property="og:locale" content="en_US" />',
                      '<meta property="og:locale" content="ar_AE" />', 1)

    # 4. force Arabic before main.js runs (version-agnostic)
    out, n = re.subn(
        r'(<script src="\.\./assets/js/main\.js[^"]*"></script>)',
        r'<script>try{localStorage.setItem("af-lang","ar")}catch(e){}</script>\n\1',
        out, count=1,
    )
    assert n == 1, "could not find main.js <script> tag to inject the af-lang setter"

    # 5. mark as generated
    out = out.replace("<head>",
                      "<head>\n<!-- GENERATED by tools/build.py from ../index.html — do not edit by hand -->",
                      1)

    ar_dir = ROOT / "ar"
    ar_dir.mkdir(exist_ok=True)
    (ar_dir / "index.html").write_text(out, encoding="utf-8")
    print("wrote ar/index.html")


def refresh_sitemap():
    p = ROOT / "sitemap.xml"
    xml = p.read_text(encoding="utf-8")
    if "<lastmod>" in xml:
        xml = re.sub(r"<lastmod>[^<]*</lastmod>", f"<lastmod>{TODAY}</lastmod>", xml)
    else:
        xml = xml.replace("</loc>", f"</loc><lastmod>{TODAY}</lastmod>")
    p.write_text(xml, encoding="utf-8")
    print(f"sitemap.xml lastmod -> {TODAY}")


if __name__ == "__main__":
    build_ar()
    refresh_sitemap()
    print("done.")
