# -*- coding: utf-8 -*-
"""English text for the workshop pages, keyed by the slug used in gen_workshops.py.

The Arabic in WORKSHOPS stays the source of record for what each workshop is;
this file mirrors it field for field so gen_workshops.py can emit an English
page beside every Arabic one. Lists must stay in the same order and the same
length as their Arabic counterparts — gen_workshops.py asserts that.

The workshops themselves are delivered in Arabic; the pages say so.
"""

EN = {
"smart-event-management-ai": {
    "topic": "Artificial Intelligence",
    "level": "Intermediate",
    "duration": "Two training days (10 hours) — can be condensed into a single day",
    "prereq": "Basic computer and internet skills, and hands-on experience organising at least one event or conference",
    "overview": "The workshop offers a practical framework for putting generative AI tools to work across the whole life cycle of an academic event — from the first idea for a conference or seminar through to the closing impact report — cutting delivery time, raising the quality of the output and automating repetitive work for organising teams in universities and information institutions.",
    "objectives": [
        "Map the AI tools that suit each stage of event management",
        "Build a complete event plan (scope, timeline, indicative budget) with help from generative models",
        "Automate invitations and correspondence, and draft multilingual promotional copy",
        "Use AI to screen abstracts, schedule sessions and assign reviewers",
        "Design live dashboards for registration, attendance and engagement",
        "Produce the closing report, analyse feedback and measure event impact automatically",
    ],
    "contents": [
        "The academic event life cycle and where AI enters at each stage",
        "Prompt engineering for planning tasks: the event brief, the timeline, risk analysis",
        "Automating marketing and correspondence: content generation, translation, channel scheduling",
        "Managing scientific papers: abstract screening, similarity detection, matching papers to reviewers",
        "Registration and participant service: chatbots, FAQs, live support",
        "Dashboards and decision making during the event using live data",
        "After the event: session transcription, minutes generation, impact reports and recommendations",
        "Governance, ethics of use and protection of participant data",
    ],
    "outcomes": [
        "Design a delivery plan for an academic event with a specific AI tool assigned to each task",
        "Build a reusable prompt library for organising teams",
        "Create a dashboard tracking registration, attendance and engagement",
        "Prepare an automated closing-report template linking objectives to results and impact",
        "Draw up a governance and data-protection checklist for using these tools",
    ],
    "audience": [
        "Event and conference coordinators and managers in universities and information centres",
        "Staff in corporate communication and public relations departments of libraries",
        "Members of scientific and organising committees for conferences",
        "Librarians tasked with organising seminars and workshops",
    ],
},
"institutional-innovation-ai": {
    "topic": "Artificial Intelligence",
    "level": "Intermediate to advanced",
    "duration": "Two training days (12 hours)",
    "prereq": "Managerial or supervisory experience in an information centre or library, and general awareness of AI concepts",
    "overview": "The workshop focuses on turning AI from a scattering of individual tools into a sustainable institutional capability: how an information centre builds a culture of innovation, identifies high-value application opportunities, manages a portfolio of initiatives, measures return, and establishes responsible governance for adoption.",
    "objectives": [
        "Analyse the centre's digital maturity and its readiness to adopt AI",
        "Use opportunity-discovery tools to rank use cases by value and feasibility",
        "Design an operating model for innovation: roles, processes, an experiment lab, a funding cycle",
        "Manage a portfolio of AI initiatives from idea to scale-up",
        "Build performance and return-on-investment indicators for AI initiatives",
        "Draft a governance, ethics and responsible-use policy that respects privacy",
    ],
    "contents": [
        "Institutional innovation concepts and digital maturity models for information institutions",
        "A map of AI use cases across reference services, cataloguing, research and administration",
        "A prioritisation method: the value-versus-effort matrix, and short initiative cards",
        "Designing an internal proof-of-concept lab and managing its risks",
        "Change management, team capability building and a culture of experimentation",
        "Measuring impact: operational indicators, user satisfaction, savings in time and cost",
        "Governance: data policy, transparency, bias, intellectual property",
        "An annual roadmap for phased adoption",
    ],
    "outcomes": [
        "Produce an assessment of their institution's readiness to adopt AI",
        "Build an initial portfolio of three to five initiatives ranked by priority",
        "Design a simplified governance model for AI use in their centre",
        "Set out a twelve-month adoption roadmap with clear measurement indicators",
    ],
    "audience": [
        "Directors and deputy directors of libraries, information and research centres",
        "Heads of technical and service departments, and supervisors",
        "Digital transformation and strategic planning officers in knowledge institutions",
        "Leaders of innovation initiatives in government and academic bodies",
    ],
},
"ai-prompt-engineering-libraries": {
    "topic": "Artificial Intelligence",
    "level": "Introductory to intermediate",
    "duration": "Two training days (10 hours) — 70% hands-on",
    "prereq": "No programming experience required; general computer use and familiarity with generative AI tools is enough",
    "overview": "A hands-on workshop built on the trainer's book on AI prompt engineering in libraries. It takes participants from writing ad-hoc prompts to designing structured, reusable prompts that serve cataloguing, reference service, bibliometric analysis and content production inside the library.",
    "objectives": [
        "Understand how large language models work and the limits of using them in a library setting",
        "Master the parts of an effective prompt: role, context, task, constraints, output format",
        "Apply advanced patterns: few-shot prompting, chain of thought, stepwise analysis, templates",
        "Build a unified institutional prompt library for recurring library tasks",
        "Assess output quality and handle hallucination, bias and data errors",
        "Document prompts, share them and version them across the team",
    ],
    "contents": [
        "Generative model fundamentals: capabilities, limits, core concepts",
        "Anatomy of an effective prompt, and building a unified template for the library",
        "Cataloguing and metadata prompts: suggested descriptors, subject headings, summaries",
        "Reference service prompts: guided answers, research guides, source recommendations",
        "Analysis prompts: preliminary literature reviews, study summaries, bibliometric extraction",
        "Content production prompts: awareness posts, newsletters, training material",
        "Quality assurance: checklists, tests, dealing with hallucination",
        "Governance: privacy, copyright, disclosing the use of AI",
    ],
    "outcomes": [
        "Write structured prompts to a unified template for any library task",
        "Produce a documented library of at least ten ready prompts for their department's work",
        "Apply at least three advanced patterns to real scenarios",
        "Build a checklist for assessing AI output before relying on it",
    ],
    "audience": [
        "Library and information specialists across all departments",
        "Cataloguers, metadata specialists and technical services staff",
        "Reference service and bibliographic instruction specialists",
        "Researchers and postgraduate students in library and information science",
    ],
},
"digital-repositories-standards": {
    "topic": "Digital Repositories",
    "level": "Intermediate to advanced",
    "duration": "Three training days (15 hours)",
    "prereq": "Basic knowledge of metadata and library systems; prior reading on open access is helpful",
    "overview": "A comprehensive workshop covering the whole life cycle of building an institutional digital repository: from the needs study and policy setting, through platform selection (DSpace, Fedora and others), metadata architecture and workflow design, to operation, long-term digital preservation and impact measurement.",
    "objectives": [
        "Draft the repository's vision, objectives and policies (deposit, content, rights, privacy)",
        "Compare open-source repository platforms and choose the one that best fits the institution",
        "Design a metadata schema compatible with Dublin Core and MODS, and OAI-PMH interoperability policy",
        "Build deposit, review and publication workflows and assign persistent identifiers (DOI/Handle)",
        "Apply the OAIS model and the principles of long-term digital preservation",
        "Set repository performance indicators (availability, growth, usage, citation)",
    ],
    "contents": [
        "Digital repository concepts, their types, and their relationship to open access and open science",
        "The needs study, stakeholder analysis and building the business case",
        "Governing policies: self and mediated deposit, copyright, embargo periods",
        "System architecture: platforms, hosting, integration with university systems",
        "Metadata: schemas, mandatory fields, controlled vocabularies, interoperability",
        "Workflow: deposit forms, review steps, quality assurance, persistent identifiers",
        "Digital preservation: OAIS, file formats, backup, contingency plans",
        "Launch, promotion, operational governance and measurement indicators",
    ],
    "outcomes": [
        "Produce a complete policy document for an institutional digital repository",
        "Design a workable metadata schema and deposit workflow",
        "Draw up a reasoned comparison matrix for choosing the repository platform",
        "Build a long-term digital preservation plan and a performance dashboard",
    ],
    "audience": [
        "Digital repository specialists in academic and research libraries",
        "Directors of university libraries and research centres",
        "Metadata, systems and research support specialists",
        "Officers responsible for open access and institutional publishing initiatives",
    ],
},
"library-services-ai-ml": {
    "topic": "Artificial Intelligence",
    "level": "Intermediate",
    "duration": "Two training days (12 hours)",
    "prereq": "Experience delivering library services; no advanced programming skills required",
    "overview": "The workshop looks at how AI and machine learning are reshaping library services: discovery and recommendation, automated reference service, content accessibility, user behaviour analysis and service personalisation — with practical applications and tools ready for gradual adoption.",
    "objectives": [
        "Identify the library services most open to improvement through AI",
        "Design a simple recommendation engine for the library's resources and services",
        "Build an automated reference assistant (chatbot) grounded in the library's knowledge base",
        "Use machine learning on circulation and usage data to support decisions",
        "Apply content accessibility tools: OCR, transcription, translation, alternative text",
        "Evaluate new services through controlled trials and user satisfaction measurement",
    ],
    "contents": [
        "A map of library services and where AI and machine learning can improve them",
        "Discovery and recommendation systems: principles, the data required, ready tools",
        "The automated reference assistant: building the knowledge base, linking to sources, quality control",
        "Usage analytics: data collection, predictive models, dashboards",
        "Content accessibility and digital inclusion with AI tools",
        "Service personalisation, privacy management and user satisfaction",
        "An experimental method: control group, indicators, improvement cycle",
        "A phased adoption plan and change management",
    ],
    "outcomes": [
        "Design one AI-enhanced library service ready for trial",
        "Build a prototype automated reference assistant or recommendation engine",
        "Produce a dashboard for analysing service usage",
        "Draw up an impact and satisfaction measurement plan for the new service",
    ],
    "audience": [
        "Public services, reference and user services specialists",
        "Staff responsible for library systems, discovery layers and digital portals",
        "Library data analysts and reporting officers",
        "Managers of service and experience development in libraries",
    ],
},
"strategic-planning-big-data": {
    "topic": "Strategic Planning",
    "level": "Advanced / leadership",
    "duration": "Two training days (12 hours) plus a follow-up session",
    "prereq": "A supervisory or leadership post, and prior involvement in preparing operational plans",
    "overview": "A leadership workshop connecting modern strategic planning tools to the reality of big data: how an information institution turns its data into a strategic advantage, builds a flexible plan grounded in indicators and foresight, and keeps pace with shifts in information behaviour and technology.",
    "objectives": [
        "Analyse the internal and external environment with modern, data-backed tools",
        "Draft the strategic direction (mission, vision, values, objectives) for an information institution",
        "Build a strategy map and balanced performance indicators (BSC/OKR)",
        "Fold big-data analytics and foresight into the planning cycle",
        "Manage risk, scenarios and contingency plans",
        "Align budget, resources and initiatives with strategic priorities",
    ],
    "contents": [
        "Contemporary strategic planning concepts and what is particular to information institutions",
        "Big data: its sources in libraries, its governance, and turning it into decision insight",
        "Analysis tools: PESTEL, the five forces, quantitative SWOT, stakeholder analysis",
        "Foresight: trends, weak signals, scenario building",
        "The strategy map, the indicator system and its link to initiatives",
        "Delivery governance: follow-up, periodic review, performance management",
        "Change management and strategic communication with users and partners",
        "A hands-on session: a draft strategic plan for the participant's own institution",
    ],
    "outcomes": [
        "Produce a draft strategic framework for their institution (direction, objectives, indicators)",
        "Build a strategy map and a balanced performance dashboard",
        "Design two future scenarios and a response plan for each",
        "Set out a mechanism for aligning the annual budget with strategic priorities",
    ],
    "audience": [
        "Directors of libraries and information centres, and their deputies",
        "Planning, organisational development and quality officers",
        "Leaders of digital transformation and knowledge management initiatives",
        "Candidates for leadership posts in information institutions",
    ],
},
"technical-operations-digital-library": {
    "topic": "Technical Operations",
    "level": "Intermediate",
    "duration": "Three training days (15 hours)",
    "prereq": "Working in — or supervising — acquisitions, cataloguing, authority control or serials",
    "overview": "The workshop redesigns the library's technical operations (acquisitions, cataloguing, authority control, serials, electronic resources) to suit a digital environment: a unified workflow, productivity indicators, automation of repetitive tasks, and system integration.",
    "objectives": [
        "Map the current technical processes and identify bottlenecks and waste",
        "Redesign the workflow on quality and efficiency (Lean) principles",
        "Unify cataloguing and acquisitions policies and quality control",
        "Automate repetitive tasks through system tools, light scripting and AI",
        "Manage electronic resources, their life cycle (ERM) and their licences",
        "Build productivity and quality indicators for technical operations, and periodic reporting",
    ],
    "contents": [
        "The technical operations system in a digital library and how its parts relate",
        "Process maps, cycle-time analysis and points of delay",
        "Modern acquisitions: purchasing models, demand-driven acquisition, subscriptions, PDA/DDA",
        "Cataloguing in a digital environment: copy cataloguing, batches, automated loading",
        "Authority control, quality control and automated record validation",
        "Electronic resource management: licences, activation, COUNTER usage statistics",
        "Automation: tools such as MarcEdit, scripting, and integration through system APIs",
        "Productivity and quality dashboards, and a culture of continuous improvement",
    ],
    "outcomes": [
        "Draw an improved map of one technical process with an estimate of the savings expected",
        "Produce a unified policy and procedures manual for their department",
        "Apply at least one automation tool to a real recurring task",
        "Build a monthly productivity and quality dashboard",
    ],
    "audience": [
        "Heads and members of acquisitions, cataloguing, serials and technical services departments",
        "Authority control and quality assurance specialists",
        "Electronic resources and library systems officers",
        "Supervisors responsible for process development in libraries",
    ],
},
"marc21-advanced-cataloging": {
    "topic": "Metadata &amp; Cataloguing",
    "level": "Advanced",
    "duration": "Three training days (18 hours) — intensively hands-on",
    "prereq": "Command of MARC 21 basics and descriptive cataloguing, and real work on an integrated library system",
    "overview": "An advanced workshop that goes beyond MARC 21 basics into complex applications: multi-level records, linking between records, batch editing, format conversion, and integration with semantic web data — with exercises on difficult cataloguing cases.",
    "objectives": [
        "Master the complex fields in MARC 21 (76X–78X linking fields, 880 alternate scripts, local fields)",
        "Catalogue continuing and integrating resources, special materials and electronic resources",
        "Carry out batch editing and conditional replacement using tools such as MarcEdit",
        "Convert records between MARC 21, MARCXML, MODS and Dublin Core",
        "Validate records automatically, and detect and fix errors",
        "Connect MARC 21 to BIBFRAME and semantic web data as a route forward",
    ],
    "contents": [
        "A quick review of MARC 21 record structure, delimiters, indicators and subfield codes",
        "Advanced fields: linking entries (76X–78X), analysis, alternate graphic representation (880)",
        "Special cases: serials, series, collections, manuscripts, maps, media",
        "Batch editing: regular expressions, tasks and templates in MarcEdit",
        "Import, export, OAI harvesting, automated loading and duplicate detection",
        "Conversion between formats and metadata schemas, and quality control afterwards",
        "Validation: audit tools, error reports, correction plans",
        "From MARC to BIBFRAME: concepts, differences, transition scenarios",
    ],
    "outcomes": [
        "Catalogue complex resources in MARC 21 accurately and consistently with policy",
        "Carry out a batch editing project on a real set of records",
        "Convert a set of records between two formats with a quality control report",
        "Produce a checklist for automated record validation in their own system",
    ],
    "audience": [
        "Experienced cataloguers and metadata specialists",
        "Staff responsible for record loading and bibliographic databases",
        "Supervisors of cataloguing and technical services departments",
        "Systems specialists involved in bibliographic data migration",
    ],
},
"rda-lcsh-cataloging": {
    "topic": "Metadata &amp; Cataloguing",
    "level": "Intermediate",
    "duration": "Three training days (18 hours)",
    "prereq": "Basic knowledge of cataloguing and MARC 21; well suited to those moving from AACR2 to RDA",
    "overview": "A hands-on workshop combining descriptive cataloguing under RDA and the IFLA-LRM model with subject cataloguing and authority control under the Library of Congress Subject Headings (LCSH), with exercises on varied material and the results mapped to MARC 21 fields.",
    "objectives": [
        "Understand the foundations of RDA, the IFLA-LRM model, and entity and relationship concepts",
        "Record the core description elements and relationships under RDA in a MARC 21 environment",
        "Build controlled access points for persons, corporate bodies and works",
        "Analyse subject content and formulate main and subdivided LCSH headings",
        "Use subdivisions (form, topical, geographic, chronological) and build heading strings",
        "Keep descriptive and subject cataloguing consistent with library policy",
    ],
    "contents": [
        "From AACR2 to RDA: the philosophy, the structure, the working tools (RDA Toolkit)",
        "The IFLA-LRM model: entities, attributes, relationships and their effect on description",
        "RDA elements: title, responsibility, edition, production/publication, physical description, series",
        "Controlled access points and relationships between entities (authors, works, expressions)",
        "Subject analysis: determining content, subject policy, how many headings",
        "LCSH: heading types, subdivisions, strings, search and verification tools",
        "Mapping to MARC 21 fields (1XX, 6XX, 7XX, 8XX) and quality control",
        "Comprehensive exercises on books, serials, electronic resources and audiovisual material",
    ],
    "outcomes": [
        "Create complete descriptive records under RDA for several material types",
        "Formulate accurate, consistent LCSH headings with the right subdivisions",
        "Build controlled access points and document relationships between entities",
        "Produce a short policy guide for descriptive and subject cataloguing in their library",
    ],
    "audience": [
        "Cataloguers and descriptive and subject cataloguing specialists",
        "Authority control and subject headings specialists",
        "Librarians newly moving to RDA",
        "Postgraduate students and trainers in knowledge organisation",
    ],
},
"integrated-library-systems": {
    "topic": "Library Systems",
    "level": "Intermediate",
    "duration": "Three training days (15 hours)",
    "prereq": "Working in a library that uses an integrated system; system administration experience is not required",
    "overview": "An operational workshop covering the modules of an integrated library system (cataloguing, acquisitions, circulation, serials, the public catalogue) and its daily administration: permissions, policies, reports, maintenance and integration with other services — with examples from systems such as Koha, Symphony and Horizon.",
    "objectives": [
        "Grasp the architecture of an integrated library system and how its modules relate",
        "Configure circulation policies, fines, and patron and material types",
        "Manage permissions, staff accounts and audit logs",
        "Run the acquisitions and serials modules, and track orders and budget",
        "Extract operational and statistical reports and dashboards",
        "Manage routine maintenance, backup and service continuity plans",
    ],
    "contents": [
        "The parts of an integrated library system and the shared database",
        "System setup: patron types, materials, locations, the work calendar",
        "The circulation module: rules, holds, renewals, fines, notices",
        "The acquisitions and serials modules: purchase orders, vendors, budget, claiming",
        "The public catalogue (OPAC/discovery): configuration, interfaces, the patron account",
        "Reports: prebuilt, custom, direct queries, export",
        "Security, permissions, the audit log and protection of patron data",
        "Maintenance: updates, backup, the contingency plan, fault management",
    ],
    "outcomes": [
        "Configure a full set of circulation policies for one patron type and material type",
        "Create a set of periodic operational reports for their department",
        "Produce a permissions matrix for staff using the system",
        "Draw up a maintenance, backup and service continuity plan",
    ],
    "audience": [
        "Library system operators in circulation, cataloguing, acquisitions and serials",
        "New system librarians",
        "Library supervisors responsible for daily operation",
        "IT support teams working alongside the library",
    ],
},
"digital-collections": {
    "topic": "Repositories &amp; Digital Collections",
    "level": "Intermediate",
    "duration": "Two training days (12 hours)",
    "prereq": "General knowledge of collection development and metadata",
    "overview": "The workshop covers planning, building, growing, organising and delivering digital collections: from the digital collection development policy and content selection through digitisation or digital acquisition, description, rights, access, usage measurement and periodic review.",
    "objectives": [
        "Draft a development policy for digital collections with selection and withdrawal criteria",
        "Identify sources of digital content (digitisation, deposit, purchase, open access, donation)",
        "Design an organisational structure and descriptive, administrative and structural metadata for the collection",
        "Handle copyright, licensing and access questions",
        "Build access and discovery interfaces and connect them to the catalogue and repository",
        "Measure collection usage and evaluate and review it periodically",
    ],
    "contents": [
        "What a digital collection is, its types, and how it relates to the repository and the archive",
        "Digital collection development policy: scope, priorities, quality criteria",
        "Content sources: digitisation projects, deposit, acquisition, partnerships",
        "Metadata for digital collections: schemas, levels of description, mandatory fields",
        "Rights: intellectual property, Creative Commons licences, rights statements",
        "Access and discovery: platforms, interfaces, improving visibility, interlinking",
        "Preservation, file management, formats and copies",
        "Evaluation: usage indicators, user satisfaction, collection review",
    ],
    "outcomes": [
        "Produce a draft development policy for a specific digital collection",
        "Design a metadata description template for the collection and a plan for organising it",
        "Build a rights and licensing matrix for the collection's items",
        "Draw up an access, usage measurement and periodic evaluation plan",
    ],
    "audience": [
        "Collection development and digital acquisitions specialists",
        "Digitisation and digital library specialists",
        "Curators of special and heritage collections",
        "Digital content officers in libraries and information centres",
    ],
},
"information-document-security": {
    "topic": "Archives &amp; Information Security",
    "level": "Intermediate",
    "duration": "Two training days (12 hours)",
    "prereq": "Working in records management, archives, systems or digital libraries",
    "overview": "The workshop builds a practical understanding of information and document security in information institutions: information classification, access control, protecting the integrity of digital documents, privacy and compliance, and incident response — with practice aligned to standards such as ISO 27001 and ISO 15489 for records management.",
    "objectives": [
        "Classify information and documents by sensitivity and set handling policies for them",
        "Design access controls (identity, permissions, least privilege)",
        "Protect the integrity of digital documents and prevent tampering (signatures, hashes, audit logs)",
        "Apply privacy and personal data protection principles and regulatory compliance",
        "Draw up backup, recovery and business continuity plans",
        "Build a response plan for information security incidents and document leaks",
    ],
    "contents": [
        "Information security concepts: confidentiality, integrity, availability, applied to documents",
        "Information classification, handling policies and labelling",
        "Identity and access management: authentication, authorisation, permission review",
        "Protecting digital documents: encryption, digital signatures, timestamps, audit logs",
        "Privacy and compliance: data protection principles, retention, secure disposal",
        "Common threats: phishing, malware, social engineering, the insider threat",
        "Backup, recovery and business continuity (BCP/DRP)",
        "Incident response: detection, containment, investigation, lessons learned",
    ],
    "outcomes": [
        "Set out an information classification scheme and handling policy for their institution",
        "Design a role-based access control matrix",
        "Produce a documented backup and recovery plan",
        "Build a simplified response playbook for document-leak incidents",
    ],
    "audience": [
        "Records, archives and document management specialists and managers",
        "Systems and digital library officers",
        "Compliance and data protection officers",
        "IT teams responsible for protecting institutional content",
    ],
},
"digital-preservation-manuscripts": {
    "topic": "Archives &amp; Digital Heritage",
    "level": "Intermediate to advanced",
    "duration": "Three training days (18 hours) — includes lab sessions",
    "prereq": "Working with heritage collections, manuscripts or archives, or supervising a digitisation project",
    "overview": "A specialist workshop built on the trainer's experience and his book on digitising Arab heritage. It covers planning digitisation projects for manuscripts and heritage material, imaging and quality specifications, description, and long-term digital preservation policy under the OAIS model and trustworthiness standards.",
    "objectives": [
        "Plan a heritage digitisation project: objectives, priorities, resources, risk management",
        "Set digital imaging specifications (resolution, colour depth, formats, calibration targets)",
        "Establish safe handling procedures for manuscripts during digitisation",
        "Design the description and metadata structure (descriptive, technical, administrative, preservation) for heritage material",
        "Apply the OAIS model, long-term preservation policy and integrity verification",
        "Build an access plan that respects rights and the cultural sensitivity of the content",
    ],
    "contents": [
        "The feasibility study, setting priorities and criteria for selecting material to digitise",
        "The digitisation lab: equipment, lighting, calibration, workspace control",
        "Quality specifications: FADGI/Metamorfoze, master files and use copies",
        "Handling and physical conservation of manuscripts during the project",
        "Metadata: MODS, METS, PREMIS, and manuscript description (TEI as an option)",
        "Digital preservation: OAIS, archival formats, integrity verification (checksums), migration",
        "Storage, multiple copies and disaster recovery plans",
        "Access: platforms, usage rights, cultural sensitivity, manuscript viewers (IIIF)",
    ],
    "outcomes": [
        "Produce a complete project plan for a heritage digitisation project",
        "Write a technical specification document for imaging and quality control",
        "Design a descriptive and preservation metadata template for heritage material",
        "Set out a long-term digital preservation policy with integrity verification procedures",
    ],
    "audience": [
        "Curators of manuscripts and special and heritage collections",
        "Digitisation and preservation specialists in national libraries and archives",
        "Managers of heritage digitisation projects",
        "Researchers and staff in cultural heritage institutions",
    ],
},
"repositories-archiving-ai-open-access": {
    "topic": "Digital Repositories",
    "level": "Advanced",
    "duration": "Two training days (12 hours)",
    "prereq": "Prior experience with digital repositories, digital archiving or research data management",
    "overview": "A forward-looking workshop joining three threads — digital repositories, archiving, and long-term preservation — and rereading them in the light of two large shifts: the spread of generative AI, and the entrenchment of open-access and open-science policy, with application scenarios and governance.",
    "objectives": [
        "Analyse the effect of open access and funder policy on the role of institutional repositories",
        "Use AI to enrich metadata, control quality and improve discovery inside the repository",
        "Fold research data and its management plans into the repository",
        "Apply the FAIR principles, persistent identifiers and linking between outputs",
        "Strengthen trustworthiness in the digital archive (CoreTrustSeal / OAIS)",
        "Draft governance for AI use in the repository that preserves integrity and transparency",
    ],
    "contents": [
        "The shifting landscape: open access, funder mandates, open science, open data",
        "AI inside the repository: descriptor generation, classification, duplicate detection, translation",
        "Research data management: management plans, acquisition, description, data citation",
        "The FAIR principles and persistent identifiers (DOI, ORCID, ROR) and linking networks",
        "Long-term preservation, trustworthiness, and assessment and certification standards",
        "Measuring impact: altmetrics, dashboards, compliance reporting",
        "Risks: the quality of automated output, bias, copyright, machine-generated content",
        "A roadmap for developing the repository over the next two years",
    ],
    "outcomes": [
        "Produce an assessment of their repository's position in the light of open-access policy",
        "Design one AI application scenario for metadata enrichment, with its controls",
        "Build a checklist for aligning the repository with the FAIR principles",
        "Set out a two-year development roadmap for the repository",
    ],
    "audience": [
        "Managers and supervisors of institutional digital repositories",
        "Research support and research data management specialists",
        "Open access and publishing policy officers in universities",
        "Digital archiving and long-term preservation specialists",
    ],
},
}
